title: Henry Symons, PhD # your name (or website title) here
logo: "/images/ProfilePicture_HS.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  With a PhD and academic research positions in chemistry, I have an extensive background working with large and varied datasets and using advanced visualisations and statistical methods.
  <br><br>
  I am experienced in complex data analysis methods in Python, SQL and Tableau, and am now looking to apply myself in a data-focused role. 
  <br><br>
  <a href="https://www.linkedin.com/in/henrysymons/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://orcid.org/0000-0001-6926-5435">View My Academic Publications (ORCiD)</a> 
  
# 
# theme: minimal
plugins:
- jekyll-remote-theme
remote_theme: pages-themes/minimal@v0.2.0
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
